# Generated by Django 5.1.2 on 2025-01-12 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(related_name='family', through='members.FamilyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
