# Generated by Django 5.1.2 on 2025-01-12 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(1, 'Właściciel'), (2, 'Administrator'), (3, 'Członek rodziny')], default=3)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'family'], name='members_fam_user_id_b6e2d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('family', 'user'), name='unique_family_user')],
            },
        ),
    ]
