# Generated by Django 5.1.2 on 2025-01-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
