# Generated by Django 5.1.2 on 2025-01-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip',
        ),
    ]
